### ISSUE TITLE
[Feature Request] Dispenser Harvesting with Tools

### ISSUE THREAD

**Issue by Happy-Hop7** [Happy-Hop7/RealisticPlantGrowth#24]
# Description
Introduce a new feature allowing dispensers with a hoe or other tools inside to harvest plants automatically on a Redstone input. 
This feature would enhance automation in farming setups and be configurable for each plant type.

# Proposed Behavior
- Functionality: When a dispenser containing a hoe or other tool is activated facing a crop, it should attempt to harvest the crop.
- Configuration: Add a section in `GrowthModifiers.yml` to configure this behavior per plant. 

For example:
```
BAMBOO:
  min_natural_light: 15
  require_tool_for_drops:
    enabled: true
    allowed_tool_list:
      - DIAMOND_SWORD
   allow_dispenser_harvesting: true
  BiomeGroup:
    Groups:
      - Tropical
    Tropical:
      NaturalGrowthRate: 100
      NaturalDeathChance: 5
      UVLightGrowthRate: 35
      UVLightDeathChance: 15
      FertilizerBoostRate: 20
      requires-greenhouse: false  # Plant must be enclosed in a greenhouse due to harsh environmental conditions.
  Default:
    Biome: [ ] # No growth in other biomes
```

# Benefits
- Encourages automation and innovative farm designs.
- Adds flexibility for server administrators to tailor farming mechanics.
